# Generated by Django 5.2.11 on 2026-02-10 09:54

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IRISImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('staff_processed', models.IntegerField(default=0)),
                ('publications_created', models.IntegerField(default=0)),
                ('publications_updated', models.IntegerField(default=0)),
                ('links_created', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'IRIS Import Log',
                'verbose_name_plural': 'IRIS Import Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, help_text='Project logo or icon', null=True, upload_to='project_logos/')),
                ('website', models.URLField(blank=True, help_text='Project website or homepage URL')),
                ('founding_by', models.CharField(blank=True, max_length=200)),
                ('project_type', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PublicationIRIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(blank=True, help_text='Unique handle identifier from IRIS', max_length=200, null=True, unique=True, verbose_name='Handle')),
                ('id_iris', models.CharField(blank=True, help_text='Internal legacy ID', max_length=50, null=True, verbose_name='IRIS Internal ID')),
                ('titolo', models.TextField(verbose_name='Title')),
                ('anno', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('autori', models.TextField(blank=True, verbose_name='Authors')),
                ('tipo', models.CharField(blank=True, max_length=200, verbose_name='Type')),
                ('rivista', models.CharField(blank=True, max_length=500, verbose_name='Journal/Conference')),
                ('abstract', models.TextField(blank=True, verbose_name='Abstract')),
                ('doi', models.CharField(blank=True, max_length=200, verbose_name='DOI')),
                ('isbn', models.CharField(blank=True, max_length=100, verbose_name='ISBN')),
                ('issn', models.CharField(blank=True, max_length=100, verbose_name='ISSN')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='Volume')),
                ('numero', models.CharField(blank=True, max_length=50, verbose_name='Number')),
                ('pagine', models.CharField(blank=True, max_length=100, verbose_name='Pages')),
                ('editore', models.CharField(blank=True, max_length=300, verbose_name='Publisher')),
                ('luogo', models.CharField(blank=True, max_length=200, verbose_name='Place')),
                ('pdf', models.URLField(blank=True, max_length=500, verbose_name='PDF URL')),
                ('allegati', models.IntegerField(default=0, verbose_name='Attachment Count')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='URL')),
                ('stato', models.CharField(blank=True, max_length=100, verbose_name='Status')),
                ('tipologia', models.CharField(blank=True, max_length=200, verbose_name='Typology')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='Language Code')),
                ('citation', models.TextField(blank=True, verbose_name='Citation')),
                ('fulltext_available', models.BooleanField(default=False, verbose_name='Fulltext Available')),
                ('scopus_citations', models.IntegerField(default=0, verbose_name='Scopus Citations')),
                ('wos_citations', models.IntegerField(default=0, verbose_name='WOS Citations')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IRIS Publication',
                'verbose_name_plural': 'IRIS Publications',
                'ordering': ['-anno', 'titolo'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='blog_covers/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Cropped thumbnail for news listings (480x200)', null=True, upload_to='blog_thumbnails/')),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(related_name='posts', to='main.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('full_professor', 'Full Professor'), ('assoc_professor', 'Associate Professor'), ('researcher_tt', 'Researcher (RTT)'), ('researcher_a', 'Researcher (RTD-A)'), ('researcher_b', 'Researcher (RTD-B)'), ('postdoc', 'Postdoctoral Researcher'), ('research_fellow', 'Research Fellow'), ('collaborator', 'External Collaborator'), ('phd', 'PhD Student'), ('intern', 'Research Intern'), ('alumni', 'Alumni'), ('past_member', 'Past Member'), ('guest', 'Visitor Researcher')], default='phd', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Short biography')),
                ('website', models.URLField(blank=True, help_text='Personal website or homepage')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('display_order', models.IntegerField(default=0, help_text='Order in team listing (lower first)')),
                ('is_visible', models.BooleanField(default=True, help_text='Show on People page')),
                ('current_position', models.CharField(blank=True, help_text='Current position (for alumni)', max_length=200)),
                ('google_scholar', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number (international format)', max_length=128, null=True, region='IT')),
                ('codice_fiscale', models.CharField(blank=True, help_text='Italian fiscal code (primary IRIS identifier)', max_length=16, null=True, unique=True, verbose_name='Codice Fiscale')),
                ('iris_pid', models.CharField(blank=True, help_text='IRIS person identifier (e.g., rp00491) - cached from API', max_length=50, verbose_name='IRIS PID')),
                ('iris_id', models.CharField(blank=True, help_text='IRIS internal ID - cached from API', max_length=50, verbose_name='IRIS Internal ID')),
                ('iris_id_ab', models.CharField(blank=True, help_text='IRIS ID AB - cached from API', max_length=50, verbose_name='IRIS ID AB')),
                ('id_iris', models.CharField(blank=True, help_text='Legacy field for backward compatibility', max_length=50, null=True, verbose_name='Legacy IRIS ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfilePublicationIRIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posizione', models.IntegerField(default=0, verbose_name='Author Position')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_links', to='main.publicationiris')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_links', to='main.userprofile')),
            ],
            options={
                'verbose_name': 'UserProfile-Publication Link',
                'verbose_name_plural': 'UserProfile-Publication Links',
                'ordering': ['publication__anno', 'posizione'],
                'unique_together': {('user_profile', 'publication')},
            },
        ),
        migrations.AddField(
            model_name='publicationiris',
            name='authors',
            field=models.ManyToManyField(related_name='publications', through='main.UserProfilePublicationIRIS', to='main.userprofile'),
        ),
        migrations.AddIndex(
            model_name='publicationiris',
            index=models.Index(fields=['anno'], name='main_public_anno_d0120b_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationiris',
            index=models.Index(fields=['handle'], name='main_public_handle_ea4d19_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationiris',
            index=models.Index(fields=['id_iris'], name='main_public_id_iris_46511c_idx'),
        ),
    ]
