# Generated by Django 5.2.9 on 2025-12-17 09:28

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='blog_covers/')),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(related_name='posts', to='main.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('professor', 'Full Professor'), ('assoc_professor', 'Associate Professor'), ('asst_professor', 'Assistant Professor'), ('postdoc', 'Postdoctoral Researcher'), ('phd', 'PhD Student'), ('intern', 'Research Intern'), ('alumni', 'Alumni'), ('past_member', 'Past Member'), ('guest', 'Visitor Researcher')], default='phd', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Short biography')),
                ('website', models.URLField(blank=True, help_text='Personal website or homepage')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('display_order', models.IntegerField(default=0, help_text='Order in team listing (lower first)')),
                ('is_visible', models.BooleanField(default=True, help_text='Show on People page')),
                ('current_position', models.CharField(blank=True, help_text='Current position (for alumni)', max_length=200)),
                ('google_scholar', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number (international format)', max_length=128, null=True, region='IT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'user__first_name'],
            },
        ),
    ]
