# Generated by Django 5.2.8 on 2025-11-24 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('professor', 'Full Professor'), ('assoc_professor', 'Associate Professor'), ('asst_professor', 'Assistant Professor'), ('postdoc', 'Postdoctoral Researcher'), ('phd', 'PhD Student'), ('intern', 'Research Intern'), ('alumni', 'Alumni')], default='phd', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Short biography')),
                ('website', models.URLField(blank=True, help_text='Personal website or homepage')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('display_order', models.IntegerField(default=0, help_text='Order in team listing (lower first)')),
                ('is_visible', models.BooleanField(default=True, help_text='Show on People page')),
                ('current_position', models.CharField(blank=True, help_text='Current position (for alumni)', max_length=200)),
                ('google_scholar', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'user__first_name'],
            },
        ),
    ]
