# Generated by Django 5.2.8 on 2026-01-05 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRISImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('staff_processed', models.IntegerField(default=0)),
                ('publications_created', models.IntegerField(default=0)),
                ('publications_updated', models.IntegerField(default=0)),
                ('links_created', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'IRIS Import Log',
                'verbose_name_plural': 'IRIS Import Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationIRIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_iris', models.CharField(max_length=50, unique=True, verbose_name='IRIS Publication ID')),
                ('titolo', models.TextField(verbose_name='Title')),
                ('anno', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('autori', models.TextField(blank=True, verbose_name='Authors')),
                ('tipo', models.CharField(blank=True, max_length=200, verbose_name='Type')),
                ('rivista', models.CharField(blank=True, max_length=500, verbose_name='Journal/Conference')),
                ('abstract', models.TextField(blank=True, verbose_name='Abstract')),
                ('doi', models.CharField(blank=True, max_length=200, verbose_name='DOI')),
                ('isbn', models.CharField(blank=True, max_length=100, verbose_name='ISBN')),
                ('issn', models.CharField(blank=True, max_length=100, verbose_name='ISSN')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='Volume')),
                ('numero', models.CharField(blank=True, max_length=50, verbose_name='Number')),
                ('pagine', models.CharField(blank=True, max_length=100, verbose_name='Pages')),
                ('editore', models.CharField(blank=True, max_length=300, verbose_name='Publisher')),
                ('luogo', models.CharField(blank=True, max_length=200, verbose_name='Place')),
                ('pdf', models.URLField(blank=True, max_length=500, verbose_name='PDF URL')),
                ('allegati', models.IntegerField(default=0, verbose_name='Attachment Count')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='URL')),
                ('stato', models.CharField(blank=True, max_length=100, verbose_name='Status')),
                ('tipologia', models.CharField(blank=True, max_length=200, verbose_name='Typology')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IRIS Publication',
                'verbose_name_plural': 'IRIS Publications',
                'ordering': ['-anno', 'titolo'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='First Name')),
                ('cognome', models.CharField(max_length=200, verbose_name='Last Name')),
                ('id_iris', models.IntegerField(blank=True, null=True, unique=True, verbose_name='IRIS ID')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_info', to='main.userprofile')),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='StaffPublicationIRIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posizione', models.IntegerField(default=0, verbose_name='Author Position')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_links', to='main.publicationiris')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_links', to='main.staff')),
            ],
            options={
                'verbose_name': 'Staff-Publication Link',
                'verbose_name_plural': 'Staff-Publication Links',
                'ordering': ['publication__anno', 'posizione'],
                'unique_together': {('staff', 'publication')},
            },
        ),
        migrations.AddField(
            model_name='publicationiris',
            name='staff_members',
            field=models.ManyToManyField(related_name='publications', through='main.StaffPublicationIRIS', to='main.staff'),
        ),
        migrations.AddIndex(
            model_name='publicationiris',
            index=models.Index(fields=['anno'], name='main_public_anno_d0120b_idx'),
        ),
        migrations.AddIndex(
            model_name='publicationiris',
            index=models.Index(fields=['id_iris'], name='main_public_id_iris_46511c_idx'),
        ),
    ]
