# Generated by Django 5.2.9 on 2026-01-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Cropped thumbnail for news listings (480x200)', null=True, upload_to='blog_thumbnails/'),
        ),
    ]
