# Generated by Django 5.2.11 on 2026-02-14 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Room name (e.g., Conference Room A)', max_length=100, unique=True)),
                ('location', models.CharField(blank=True, help_text='Building and floor', max_length=200)),
                ('capacity', models.IntegerField(help_text='Maximum number of people')),
                ('description', models.TextField(blank=True, help_text='Room features and equipment')),
                ('is_active', models.BooleanField(default=True, help_text='Is the room available for booking?')),
                ('color', models.CharField(default='#3b82f6', help_text='Color for calendar display (hex format)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Meeting/event title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Purpose or details of the meeting')),
                ('start_time', models.DateTimeField(help_text='Start date and time')),
                ('end_time', models.DateTimeField(help_text='End date and time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main.meetingroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['start_time', 'end_time'], name='main_roomre_start_t_8f961d_idx'), models.Index(fields=['room', 'start_time'], name='main_roomre_room_id_2e4f77_idx')],
            },
        ),
    ]
