# Generated by Django 5.2.9 on 2026-01-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('founding_by', models.CharField(blank=True, max_length=200)),
                ('project_type', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('full_professor', 'Full Professor'), ('assoc_professor', 'Associate Professor'), ('researcher_tt', 'Assistant Professor'), ('researcher_a', 'Researcher (RTD-A)'), ('researcher_b', 'Researcher (RTD-B)'), ('postdoc', 'Postdoctoral Researcher'), ('phd', 'PhD Student'), ('intern', 'Research Intern'), ('alumni', 'Alumni'), ('past_member', 'Past Member'), ('guest', 'Visitor Researcher')], default='phd', max_length=20),
        ),
    ]
