# Generated by Django 5.2.8 on 2025-12-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('professor', 'Full Professor'), ('assoc_professor', 'Associate Professor'), ('asst_professor', 'Assistant Professor'), ('postdoc', 'Postdoctoral Researcher'), ('phd', 'PhD Student'), ('intern', 'Research Intern'), ('alumni', 'Alumni'), ('past_member', 'Past Member'), ('guest', 'Visitor Researcher')], default='phd', max_length=20),
        ),
    ]
