# Generated by Django 5.2.8 on 2026-02-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_irisimportlog_publicationiris_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationiris',
            name='citation',
            field=models.TextField(blank=True, verbose_name='Citation'),
        ),
        migrations.AddField(
            model_name='publicationiris',
            name='fulltext_available',
            field=models.BooleanField(default=False, verbose_name='Fulltext Available'),
        ),
        migrations.AddField(
            model_name='publicationiris',
            name='handle',
            field=models.CharField(blank=True, help_text='Unique handle identifier from IRIS', max_length=200, null=True, unique=True, verbose_name='Handle'),
        ),
        migrations.AddField(
            model_name='publicationiris',
            name='language',
            field=models.CharField(blank=True, max_length=10, verbose_name='Language Code'),
        ),
        migrations.AddField(
            model_name='publicationiris',
            name='scopus_citations',
            field=models.IntegerField(default=0, verbose_name='Scopus Citations'),
        ),
        migrations.AddField(
            model_name='publicationiris',
            name='wos_citations',
            field=models.IntegerField(default=0, verbose_name='WOS Citations'),
        ),
        migrations.AddField(
            model_name='staff',
            name='codice_fiscale',
            field=models.CharField(blank=True, help_text='Italian fiscal code (primary IRIS identifier)', max_length=16, null=True, unique=True, verbose_name='Codice Fiscale'),
        ),
        migrations.AddField(
            model_name='staff',
            name='iris_id',
            field=models.CharField(blank=True, help_text='IRIS internal ID - cached from API', max_length=50, verbose_name='IRIS Internal ID'),
        ),
        migrations.AddField(
            model_name='staff',
            name='iris_id_ab',
            field=models.CharField(blank=True, help_text='IRIS ID AB - cached from API', max_length=50, verbose_name='IRIS ID AB'),
        ),
        migrations.AddField(
            model_name='staff',
            name='iris_pid',
            field=models.CharField(blank=True, help_text='IRIS person identifier (e.g., rp00491) - cached from API', max_length=50, verbose_name='IRIS PID'),
        ),
        migrations.AlterField(
            model_name='publicationiris',
            name='id_iris',
            field=models.CharField(blank=True, help_text='Internal legacy ID', max_length=50, null=True, verbose_name='IRIS Internal ID'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id_iris',
            field=models.CharField(blank=True, help_text='Legacy field - use codice_fiscale instead', max_length=50, null=True, verbose_name='Legacy IRIS ID'),
        ),
        migrations.AddIndex(
            model_name='publicationiris',
            index=models.Index(fields=['handle'], name='main_public_handle_ea4d19_idx'),
        ),
    ]
