# Generated by Django 5.2.11 on 2026-02-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_meetingroom_roomreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='image',
            field=models.ImageField(blank=True, help_text='Room photo or icon', null=True, upload_to='room_images/'),
        ),
    ]
