# Generated by Django 5.2.9 on 2026-01-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('full_professor', 'Full Professor'), ('assoc_professor', 'Associate Professor'), ('researcher_tt', 'Researcher (RTT)'), ('researcher_a', 'Researcher (RTD-A)'), ('researcher_b', 'Researcher (RTD-B)'), ('postdoc', 'Postdoctoral Researcher'), ('research_fellow', 'Research Fellow'), ('collaborator', 'External Collaborator'), ('phd', 'PhD Student'), ('intern', 'Research Intern'), ('alumni', 'Alumni'), ('past_member', 'Past Member'), ('guest', 'Visitor Researcher')], default='phd', max_length=20),
        ),
    ]
