# Generated by Django 5.2.11 on 2026-02-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_publicationiris_keywords'),
        ('main', '0003_meetingroom_image'),
    ]

    operations = [
    ]
