# Generated by Django 5.2.9 on 2026-02-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, help_text='Project logo or icon', null=True, upload_to='project_logos/'),
        ),
    ]
