# Generated by Django 5.2.11 on 2026-02-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_merge_20260215_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_iris',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
