# Generated by Django 5.2.11 on 2026-03-03 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userprofile_avatar_iris'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('rector', 'UniMORE Rector & AImageLab Head'), ('full_professor', 'Full Professor'), ('assoc_professor', 'Associate Professor'), ('researcher_tt', 'Researcher (RTT)'), ('researcher_a', 'Researcher (RTD-A)'), ('researcher_b', 'Researcher (RTD-B)'), ('postdoc', 'Postdoctoral Researcher'), ('research_fellow', 'Research Fellow'), ('collaborator', 'External Collaborator'), ('phd', 'PhD Student'), ('intern', 'Research Intern'), ('alumni', 'Alumni'), ('past_member', 'Past Member'), ('guest', 'Visitor Researcher')], default='phd', max_length=20),
        ),
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.SlugField(help_text="Short code (e.g., 'crowd'). The link will be /go/crowd", max_length=100, unique=True)),
                ('dest', models.URLField(help_text='Destination URL to redirect to', max_length=2000)),
                ('description', models.CharField(blank=True, help_text='Optional description of what this link points to', max_length=300)),
                ('click_count', models.PositiveIntegerField(default=0, help_text='Number of times this link has been visited')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of this short link', on_delete=django.db.models.deletion.CASCADE, related_name='short_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Short Link',
                'verbose_name_plural': 'Short Links',
                'ordering': ['-created_at'],
            },
        ),
    ]
