# Generated by Django 5.2.9 on 2026-02-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.URLField(blank=True, help_text='Project website or homepage URL'),
        ),
    ]
