# Generated by Django 5.2.11 on 2026-03-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_userprofile_role_shortlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(help_text="Year or period label (e.g., '1999', '2000s', '2022–2023')", max_length=20)),
                ('title', models.CharField(help_text="Short headline (e.g., 'Foundation')", max_length=200)),
                ('icon', models.CharField(default='flag', help_text='Lucide icon name (e.g., flag, trending-up, globe, cpu, zap)', max_length=50)),
                ('description', models.TextField(help_text='Body text for this milestone')),
                ('display_order', models.IntegerField(default=0, help_text='Order on the page (lower first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'History Milestone',
                'verbose_name_plural': 'History Milestones',
                'ordering': ['display_order', 'year_label'],
            },
        ),
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.SlugField(help_text="URL anchor slug (e.g., 'vision-language')", unique=True)),
                ('title', models.CharField(help_text='Research area name', max_length=200)),
                ('icon', models.CharField(default='sparkles', help_text='Lucide icon name (e.g., images, waypoints, microscope)', max_length=50)),
                ('color', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='primary', max_length=20)),
                ('homepage_caption', models.TextField(help_text='Short description shown on the homepage card')),
                ('intro', models.TextField(help_text='Medium-length intro paragraph for the research page')),
                ('detail', models.TextField(help_text='Longer detailed paragraph for the research page')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords (linked to publications search)', max_length=500)),
                ('display_order', models.IntegerField(default=0, help_text='Order on the page (lower first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Research Area',
                'verbose_name_plural': 'Research Areas',
                'ordering': ['display_order'],
            },
        ),
    ]
