# Generated by Django 5.1.11 on 2026-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_historymilestone_researcharea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(
                choices=[
                    ('rector', 'UniMORE Rector & AImageLab Head'),
                    ('full_professor', 'Full Professor'),
                    ('assoc_professor', 'Associate Professor'),
                    ('researcher_tt', 'Researcher (RTT)'),
                    ('researcher_a', 'Researcher (RTD-A)'),
                    ('researcher_b', 'Researcher (RTD-B)'),
                    ('postdoc', 'Postdoctoral Researcher'),
                    ('secretariat_staff', 'Secretariat Staff'),
                    ('research_fellow', 'Research Fellow'),
                    ('collaborator', 'External Collaborator'),
                    ('phd', 'PhD Student'),
                    ('intern', 'Research Intern'),
                    ('alumni', 'Alumni'),
                    ('past_member', 'Past Member'),
                    ('guest', 'Visitor Researcher'),
                ],
                default='phd',
                max_length=20,
            ),
        ),
    ]
