# Generated by Django 5.2.11 on 2026-03-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_userprofile_role_secretariat_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('section', models.CharField(help_text="Dashboard section heading to group cards under (e.g. 'At a Glance')", max_length=200)),
                ('logo_type', models.CharField(choices=[('external', 'External URL'), ('lucide', 'Lucide Icon'), ('upload', 'Uploaded Image')], default='external', max_length=10)),
                ('logo_external_url', models.URLField(blank=True, help_text='External URL to a logo image')),
                ('logo_lucide_icon', models.CharField(blank=True, help_text='Lucide icon name (e.g. coins, sparkles)', max_length=100)),
                ('logo_upload', models.ImageField(blank=True, help_text='Uploaded logo image', upload_to='dashboard_logos/')),
                ('link_type', models.CharField(choices=[('external', 'External Link'), ('file', 'Downloadable File')], default='external', max_length=10)),
                ('link_url', models.URLField(blank=True, help_text='External URL for the card link')),
                ('link_file', models.FileField(blank=True, help_text='File available for download', upload_to='dashboard_files/')),
                ('display_order', models.IntegerField(default=0, help_text='Order within the section (lower first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Card',
                'verbose_name_plural': 'Dashboard Cards',
                'ordering': ['section', 'display_order'],
            },
        ),
    ]
