# Generated by Django 5.2.11 on 2026-03-15 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_dashboardcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly slug', max_length=250, unique=True)),
                ('content', models.TextField(help_text='Page content (supports Markdown)')),
                ('display_order', models.IntegerField(default=0, help_text='Order within parent (lower first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Published pages are visible to all authenticated users')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_pages_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent page for hierarchical organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='main.wikipage')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_pages_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wiki Page',
                'verbose_name_plural': 'Wiki Pages',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WikiPageChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_title', models.CharField(blank=True, help_text='Leave blank to keep current title', max_length=200)),
                ('proposed_content', models.TextField(help_text='Suggested content changes')),
                ('change_description', models.TextField(help_text='Explanation of why these changes are needed')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text="Reviewer's notes")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='main.wikipage')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wiki Change Request',
                'verbose_name_plural': 'Wiki Change Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WikiPageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.CharField(blank=True, help_text='Brief description of changes', max_length=500)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_edits', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='main.wikipage')),
            ],
            options={
                'verbose_name': 'Wiki Page Version',
                'verbose_name_plural': 'Wiki Page Versions',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['slug'], name='main_wikipa_slug_05d5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['parent', 'display_order'], name='main_wikipa_parent__8c0246_idx'),
        ),
        migrations.AddIndex(
            model_name='wikipagechangerequest',
            index=models.Index(fields=['status', '-created_at'], name='main_wikipa_status_28d203_idx'),
        ),
        migrations.AddIndex(
            model_name='wikipagechangerequest',
            index=models.Index(fields=['page', 'status'], name='main_wikipa_page_id_aee041_idx'),
        ),
        migrations.AddIndex(
            model_name='wikipageversion',
            index=models.Index(fields=['page', '-edited_at'], name='main_wikipa_page_id_b1f186_idx'),
        ),
    ]
