# Generated by Django 5.2.11 on 2026-03-15 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_wikipage_wikipagechangerequest_wikipageversion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='slug',
            field=models.SlugField(help_text='URL-friendly slug (auto-generated if not provided)', max_length=250, unique=True),
        ),
        migrations.CreateModel(
            name='WikiImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Wiki image', upload_to='wiki_images/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, help_text='Image description', max_length=200)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wiki Image',
                'verbose_name_plural': 'Wiki Images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
