# Generated by Django 5.2.11 on 2026-03-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_wikipage_slug_wikiimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalRedirects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_slug', models.SlugField(help_text='Source slug used in <current_site>/<src_slug>', max_length=100, unique=True)),
                ('custom_dest', models.URLField(help_text='Destination URL', max_length=2000)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External Redirect',
                'verbose_name_plural': 'External Redirects',
                'ordering': ['-created_at'],
            },
        ),
    ]
