# Generated by Django 5.2.11 on 2026-05-02 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_externalredirects'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for this attachment', max_length=200)),
                ('file', models.FileField(help_text='Attachment file', upload_to='news_attachments/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='main.post')),
            ],
            options={
                'ordering': ['name', '-uploaded_at'],
            },
        ),
    ]
