# Generated by Django 5.2.12 on 2026-03-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglist', '0006_plus_addressing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectroleroute',
            name='roles',
            field=models.JSONField(default=list, help_text="List of role keys that should receive this mail, e.g. ['professor','phd']"),
        ),
        migrations.AlterField(
            model_name='subjectroleroute',
            name='tag',
            field=models.CharField(help_text="Plus-address suffix, e.g. 'staff' for aimagelab+staff@unimore.it", max_length=100, unique=True),
        ),
    ]
