# Generated by Django 5.2.12 on 2026-04-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglist', '0008_outgoingemail_unique_and_sending_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingemail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending moderation'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_approved', 'Auto-approved'), ('blacklisted', 'Rejected (blacklisted sender)'), ('not_direct_recipient', 'Rejected (not directly addressed)')], default='pending', max_length=20),
        ),
    ]
